# Generated by Django 5.0.3 on 2024-05-09 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_web', '0002_alter_kisi_kisimail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kisi',
            old_name='KisiMail',
            new_name='user',
        ),
    ]
